version: '3'

services:
  backend:
    image: backend-image
    build:
      context: ./backend
    volumes:
      - ./backend:/kronosdb
    ports:
      - "3000:3000"
  frontend:
    image: frontend-image
    build:
      context: ./frontend
    volumes:
      - ./frontend:/kronosdb
    ports:
      - "5173:5173"
